<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyDescription>Overhauled and improved version of AMP Configurable by Materous</AssemblyDescription>
    <AssemblyName>AMP_Configurable</AssemblyName>
    <AssemblyCopyright>Copyright ©  2021</AssemblyCopyright>
    <Product>AMPED - Auto Map Pins Enhanced</Product>
    <Version>1.3.7</Version>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>AMP_Configurable</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="6000.0.46" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <Import Project=".\valheim.targets" />

  <Target Name="Copy" AfterTargets="Build">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(ProjectDir)\bin\Release\AMPED-AutoMapPinsEnhanced_v1.3.7\plugins\&quot; /q /y /i" />
    <Exec Command="xcopy &quot;$(ProjectDir)\AMP_Enhanced\amp_pin_types.json&quot; &quot;$(ProjectDir)\bin\Release\AMPED-AutoMapPinsEnhanced_v1.3.7\plugins\AMP_Enhanced\&quot; /q /y /i" />
    <Exec Command="xcopy &quot;$(ProjectDir)\AMP_Enhanced\pin-icons&quot; &quot;$(ProjectDir)\bin\Release\AMPED-AutoMapPinsEnhanced_v1.3.7\plugins\AMP_Enhanced\pin-icons&quot; /c /q /y /i" />
    <Exec Command="xcopy &quot;$(ProjectDir)\..\icon.png&quot; &quot;$(ProjectDir)\bin\Release\AMPED-AutoMapPinsEnhanced_v1.3.7\&quot; /q /y /i" />
    <Exec Command="xcopy &quot;$(ProjectDir)\..\README.md&quot; &quot;$(ProjectDir)\bin\Release\AMPED-AutoMapPinsEnhanced_v1.3.7\&quot; /q /y /i" />
    <Exec Command="xcopy &quot;$(ProjectDir)\..\manifest.json&quot; &quot;$(ProjectDir)\bin\Release\AMPED-AutoMapPinsEnhanced_v1.3.7\&quot; /q /y /i" />
  </Target>
</Project>
